language: node_js
sudo: false
node_js:
- '0.12'

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  # Update npm
  - npm install -g npm@2.9.1
  - npm --version
  - npm install

script:
- ./node_modules/.bin/gulp